### PR TITLE
Adding the api collection and environment variables for OAF UAT

### PR DESCRIPTION
**Pull request by ankita10r**
## Description

* Changes for including postman collections specific to OAF UAT. 
* Set environment variables and created a collection request based on API Key

(Does not need a design doc)

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

### CODE REVIEW

**Review by fynmanoj — APPROVED** [review]

**Comment by fynmanoj** [comment]
@ankita10r Can we avoid pushing files here with the org name OAF ?

**Review by somanath21 — CHANGES_REQUESTED** [review]
@ankita10r : Please move all Postman environments including OAF UAT Postman Env to env-labs as environments are part of solution.

**Comment by fynmanoj** [comment]
Please update or close this PR : do we need to merge these @ankita10r

**Comment by ankita10r** [comment]
Its not needed for release it was to maintain uat api spec in our documentation

**Pull request closed without merging**
