### PR TITLE
Add AWS secret and access key for Importer RDBMS

### PR DESCRIPTION
**Pull request by arkadasfynarfin**
## Description

Jira link: [PHEE-358](https://fynarfin.atlassian.net/browse/PHEE-358)

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

[PHEE-358]: https://fynarfin.atlassian.net/browse/PHEE-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by arkadasfynarfin** [comment]
@fynmanoj Please review and merge this PR.
CC: @avikganguly01 @somanath21

**Comment by fynmanoj** [comment]
please check why the deployment is failing

**Review by fynmanoj — APPROVED** [review]

**Comment by arkadasfynarfin** [comment]
> please check why the deployment is failing

@fynmanoj Getting the below error.
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget "ph-ee-elasticsearch-pdb" in namespace "paymenthub" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "g2p-sandbox": current value is "zeebe"`

**Comment by arkadasfynarfin** [comment]
> please check why the deployment is failing

@fynmanoj Please merge this PR. All checks are passing now.

**Review by fynmanoj — APPROVED** [review]

**Pull request merged**
